const state={tenantId:'preview-tenant-a',role:'client_admin'},$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(action,payload={}){const r=await fetch('/api/v2/product',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,tenantId:state.tenantId,payload})}),d=await r.json();if(r.status===401){showLogin();throw Error('انتهت الجلسة')}if(!r.ok)throw Error('تعذر إتمام العملية');return d}
function notice(message,bad=false){const n=$('#notice');n.textContent=message;n.className=`notice ${bad?'bad':''}`;setTimeout(()=>n.classList.add('hidden'),3500)}
function showLogin(){$('#app').classList.add('hidden');$('#login').classList.remove('hidden')}function showApp(){$('#login').classList.add('hidden');$('#app').classList.remove('hidden');document.body.dataset.role=state.role;openView('dashboard')}
async function openView(id){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('hidden',x.id!==id));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));$('#pageTitle').textContent=$(`#nav [data-view="${id}"]`)?.textContent||'';try{if(id==='dashboard')await dashboard();if(id==='knowledge')await knowledge();if(id==='support')await support();if(id==='settings')await settings();if(id==='admin')await admin()}catch(e){notice(e.message,true)}}
async function dashboard(){const d=await api('dashboard');$('#metrics').innerHTML=[['محادثات اليوم',d.conversationsToday],['طلبات مفتوحة',d.openSupport],['مواد المعرفة',d.knowledgeCount],['استخدام الخطة',`${d.usagePercent}%`]].map(([l,v])=>`<article><b>${esc(v)}</b><span>${l}</span></article>`).join('')}
async function knowledge(){const d=await api('knowledge.list');$('#knowledgeList').innerHTML=d.items.length?d.items.map(x=>`<article><div><h3>${esc(x.title)}</h3><p>${esc(x.content)}</p></div><button class="danger" data-delete-knowledge="${esc(x.id)}">حذف</button></article>`).join(''):'<p class="empty">لا توجد مواد بعد.</p>'}
async function support(){const d=await api('support.list');$('#supportList').innerHTML=d.items.length?d.items.map(x=>`<article><div><h3>${esc(x.subject)}</h3><p>${esc(x.details||'')}</p></div><select data-support="${esc(x.id)}"><option value="open" ${x.status==='open'?'selected':''}>مفتوح</option><option value="in_progress" ${x.status==='in_progress'?'selected':''}>قيد التنفيذ</option><option value="resolved" ${x.status==='resolved'?'selected':''}>تم الحل</option></select></article>`).join(''):'<p class="empty">لا توجد طلبات دعم.</p>'}
async function settings(){const d=await api('settings.get'),f=$('#settingsForm');f.businessName.value=d.businessName||'';f.welcomeMessage.value=d.welcomeMessage||'';f.language.value=d.language||'ar'}
async function admin(){const d=await api('admin.overview');$('#adminMetrics').innerHTML=[['العملاء',d.tenants],['مواد المعرفة',d.knowledge],['طلبات مفتوحة',d.openSupport],['المحادثات',d.conversations]].map(([l,v])=>`<article><b>${esc(v)}</b><span>${l}</span></article>`).join('');const t=await api('admin.tenants');$('#tenantList').innerHTML=t.items.map(x=>`<article><div><h3>${esc(x.name)}</h3><p>${esc(x.slug)} · ${esc(x.status)}</p></div><span class="badge">${esc(x.plan)}</span></article>`).join('')}
function modal(type){$('#modalTitle').textContent=type==='knowledge'?'إضافة مادة معرفة':'طلب دعم جديد';$('#modalFields').innerHTML=type==='knowledge'?'<label>العنوان<input name="title" required maxlength="160"></label><label>المحتوى<textarea name="content" required maxlength="4000"></textarea></label>':'<label>الموضوع<input name="subject" required maxlength="160"></label><label>التفاصيل<textarea name="details" required maxlength="2000"></textarea></label>';$('#modalForm').dataset.type=type;$('#modal').showModal()}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';const r=await fetch('/api/v2/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({accessCode:$('#accessCode').value,tenantId:state.tenantId,role:$('#loginRole').value})});if(!r.ok){$('#loginError').textContent='رمز الوصول غير صحيح.';return}const d=await r.json();state.role=d.role;showApp()});
$('#nav').addEventListener('click',e=>e.target.dataset.view&&openView(e.target.dataset.view));document.addEventListener('click',async e=>{try{if(e.target.dataset.go)openView(e.target.dataset.go);if(e.target.id==='addKnowledge')modal('knowledge');if(e.target.id==='addSupport')modal('support');if(e.target.dataset.deleteKnowledge){await api('knowledge.delete',{id:e.target.dataset.deleteKnowledge});notice('تم حذف المادة.');knowledge()}}catch(err){notice(err.message,true)}});
$('#chatForm').addEventListener('submit',async e=>{e.preventDefault();const q=$('#question'),text=q.value.trim();if(!text)return;$('#chat').insertAdjacentHTML('beforeend',`<div class="message user">${esc(text)}</div>`);q.value='';try{const d=await api('assistant.ask',{question:text});$('#chat').insertAdjacentHTML('beforeend',`<div class="message assistant">${esc(d.answer)}<small>${esc(d.source||'المساعد')}</small></div>`)}catch(err){notice(err.message,true)}});
$('#supportList').addEventListener('change',async e=>{if(e.target.dataset.support){try{await api('support.update',{id:e.target.dataset.support,status:e.target.value});notice('تم تحديث حالة الطلب.')}catch(err){notice(err.message,true)}}});
$('#settingsForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('settings.update',Object.fromEntries(new FormData(e.target)));notice('تم حفظ إعدادات العميل.')}catch(err){notice(err.message,true)}});
$('#modalForm').addEventListener('submit',async e=>{e.preventDefault();try{const type=e.target.dataset.type;await api(type==='knowledge'?'knowledge.create':'support.create',Object.fromEntries(new FormData(e.target)));$('#modal').close();e.target.reset();notice('تم الحفظ بنجاح.');openView(type)}catch(err){notice(err.message,true)}});$('#modalCancel').addEventListener('click',()=>$('#modal').close());$('#logout').addEventListener('click',async()=>{await fetch('/api/v2/session',{method:'DELETE'});showLogin()});
