const crypto=require('crypto');
const STRIPE_SECRET_KEY=process.env.STRIPE_SECRET_KEY;
const STRIPE_WEBHOOK_SECRET=process.env.STRIPE_WEBHOOK_SECRET;
const APP_URL=String(process.env.APP_URL||'').replace(/\/$/,'');
const SUPABASE_URL=process.env.SUPABASE_URL;
const SUPABASE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const RESEND_API_KEY=process.env.RESEND_API_KEY;
const NOTIFICATION_FROM=process.env.NOVAIRE_NOTIFICATION_FROM||'NOVAIRE <onboarding@resend.dev>';

async function sb(path,options={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method:options.method||'GET',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json',...(options.prefer?{Prefer:options.prefer}:{})},body:options.body?JSON.stringify(options.body):undefined});const t=await r.text();if(!r.ok)throw new Error(`Supabase ${r.status}: ${t}`);return t?JSON.parse(t):null;}
function requireStripe(){if(!STRIPE_SECRET_KEY)throw new Error('STRIPE_NOT_CONFIGURED');}
async function stripe(path,params={}){requireStripe();const body=new URLSearchParams();for(const [k,v] of Object.entries(params))if(v!==undefined&&v!==null&&v!=='')body.append(k,String(v));const r=await fetch(`https://api.stripe.com/v1/${path}`,{method:'POST',headers:{Authorization:`Bearer ${STRIPE_SECRET_KEY}`,'Content-Type':'application/x-www-form-urlencoded'},body});const data=await r.json();if(!r.ok)throw new Error(`Stripe ${r.status}: ${data?.error?.message||'request failed'}`);return data;}
async function stripeGet(path,query=''){requireStripe();const r=await fetch(`https://api.stripe.com/v1/${path}${query?`?${query}`:''}`,{headers:{Authorization:`Bearer ${STRIPE_SECRET_KEY}`}});const data=await r.json();if(!r.ok)throw new Error(`Stripe ${r.status}: ${data?.error?.message||'request failed'}`);return data;}
async function readSubscription(clientId){const rows=await sb(`nsr_client_subscriptions?client_id=eq.${encodeURIComponent(clientId)}&select=*,nsr_plans(code,name,monthly_fee_aed,setup_fee_aed,stripe_monthly_price_id,stripe_setup_price_id)&limit=1`);return Array.isArray(rows)?rows[0]||null:null;}
async function readClient(clientId){const rows=await sb(`clients?id=eq.${encodeURIComponent(clientId)}&select=id,name,slug,config&limit=1`);return Array.isArray(rows)?rows[0]||null:null;}
async function findPlanCodeByPrice(priceId){if(!priceId)return null;const rows=await sb(`nsr_plans?stripe_monthly_price_id=eq.${encodeURIComponent(priceId)}&select=code&limit=1`);return Array.isArray(rows)?rows[0]?.code||null:null;}
async function findClientIdForStripeObject(obj){const meta=String(obj?.metadata?.nsr_client_id||'').trim();if(meta)return meta;const customer=typeof obj?.customer==='string'?obj.customer:obj?.customer?.id;const subscription=typeof obj?.subscription==='string'?obj.subscription:obj?.subscription?.id||(String(obj?.object||'')==='subscription'?obj.id:null);if(customer){const rows=await sb(`nsr_client_subscriptions?stripe_customer_id=eq.${encodeURIComponent(customer)}&select=client_id&limit=1`);if(Array.isArray(rows)&&rows[0]?.client_id)return rows[0].client_id;}if(subscription){const rows=await sb(`nsr_client_subscriptions?stripe_subscription_id=eq.${encodeURIComponent(subscription)}&select=client_id&limit=1`);if(Array.isArray(rows)&&rows[0]?.client_id)return rows[0].client_id;}return null;}
function escapeHtml(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
function formatAed(cents){const n=Number(cents||0)/100;return new Intl.NumberFormat('en-AE',{style:'currency',currency:'AED'}).format(n);}
async function logNotification(row){try{await sb('nsr_notification_log',{method:'POST',prefer:'return=minimal',body:row});return true;}catch(error){if(String(error.message||'').includes('23505'))return false;console.warn('BILLING NOTIFICATION LOG ERROR:',error.message);return null;}}
async function sendPaidInvoiceEmail(clientId,invoice){if(!RESEND_API_KEY)return {sent:false,skipped:true};const client=await readClient(clientId);const cfg=client?.config&&typeof client.config==='object'?client.config:{};const recipient=String(cfg.billing_email||cfg.contact_email||'').trim();if(!recipient)return {sent:false,skipped:true};const subject=`NOVAIRE | Payment received${invoice?.number?` — ${invoice.number}`:''}`;const cycleStart=invoice?.period_start?new Date(invoice.period_start*1000).toISOString().slice(0,10):null;const logRow={client_id:clientId,cycle_start:cycleStart,notification_type:`invoice_paid_${invoice?.id||'unknown'}`,recipient,subject,status:'sent',provider_message_id:null,metadata:{invoice_id:invoice?.id||null,invoice_number:invoice?.number||null,amount_paid:invoice?.amount_paid||0,hosted_invoice_url:invoice?.hosted_invoice_url||null,invoice_pdf:invoice?.invoice_pdf||null}};const inserted=await logNotification(logRow);if(inserted===false)return {sent:false,duplicate:true};const clientName=cfg.brand_name||client?.name||client?.slug||'Client';const amount=formatAed(invoice?.amount_paid);const invoiceLink=invoice?.hosted_invoice_url||invoice?.invoice_pdf||'';const html=`<div dir="rtl" style="font-family:Arial,Tahoma,sans-serif;max-width:650px;margin:auto;color:#111827;line-height:1.8"><h2>NOVAIRE Smart Response</h2><p>تم استلام دفعتكم بنجاح لخدمة <strong>${escapeHtml(clientName)}</strong>.</p><p><strong>المبلغ:</strong> ${escapeHtml(amount)}<br><strong>رقم الفاتورة:</strong> ${escapeHtml(invoice?.number||invoice?.id||'')}</p>${invoiceLink?`<p><a href="${escapeHtml(invoiceLink)}">عرض الفاتورة / الإيصال</a></p>`:''}<p style="color:#6b7280;font-size:13px">رسالة تلقائية من NOVAIRE Smart Response.</p></div>`;try{const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:NOTIFICATION_FROM,to:[recipient],subject,html})});const text=await r.text();if(!r.ok)throw new Error(`Resend ${r.status}: ${text}`);let data=null;try{data=JSON.parse(text);}catch{data={raw:text};}try{await sb(`nsr_notification_log?client_id=eq.${encodeURIComponent(clientId)}&notification_type=eq.${encodeURIComponent(logRow.notification_type)}&recipient=eq.${encodeURIComponent(recipient)}`,{method:'PATCH',prefer:'return=minimal',body:{provider_message_id:data?.id||null,status:'sent'}});}catch{}return {sent:true};}catch(error){console.error('PAID INVOICE EMAIL ERROR:',error);try{await sb(`nsr_notification_log?client_id=eq.${encodeURIComponent(clientId)}&notification_type=eq.${encodeURIComponent(logRow.notification_type)}&recipient=eq.${encodeURIComponent(recipient)}`,{method:'PATCH',prefer:'return=minimal',body:{status:'failed',metadata:{...logRow.metadata,error:String(error.message||error)}}});}catch{}return {sent:false,error:true};}}
async function persistStripeSubscription(clientId,stripeSub,customerId=null){const priceId=stripeSub?.items?.data?.[0]?.price?.id||null;const planCode=await findPlanCodeByPrice(priceId);const patch={stripe_subscription_id:stripeSub?.id||null,stripe_price_id:priceId,stripe_status:stripeSub?.status||null,auto_renew:stripeSub?!stripeSub.cancel_at_period_end:false,cancel_at_period_end:!!stripeSub?.cancel_at_period_end,stripe_current_period_end:stripeSub?.current_period_end?new Date(stripeSub.current_period_end*1000).toISOString():null,billing_updated_at:new Date().toISOString()};if(customerId)patch.stripe_customer_id=customerId;if(planCode)patch.plan_code=planCode;await sb(`nsr_client_subscriptions?client_id=eq.${encodeURIComponent(clientId)}`,{method:'PATCH',prefer:'return=minimal',body:patch});return patch;}
async function getSubscription(clientId){const sub=await readSubscription(clientId);if(!sub||!sub.stripe_subscription_id||!STRIPE_SECRET_KEY)return sub;try{const stripeSub=await stripeGet(`subscriptions/${encodeURIComponent(sub.stripe_subscription_id)}`,'expand[]=items.data.price');const patch=await persistStripeSubscription(clientId,stripeSub,sub.stripe_customer_id||null);return {...sub,...patch};}catch(error){console.warn('STRIPE SUBSCRIPTION REFRESH FAILED:',error.message);return sub;}}
async function ensureStripeCustomer(client,subscription){if(subscription?.stripe_customer_id)return subscription.stripe_customer_id;const cfg=client?.config&&typeof client.config==='object'?client.config:{};const customer=await stripe('customers',{name:client.name||client.slug,email:cfg.billing_email||cfg.contact_email||undefined,'metadata[nsr_client_id]':client.id,'metadata[nsr_client_slug]':client.slug});await sb(`nsr_client_subscriptions?client_id=eq.${encodeURIComponent(client.id)}`,{method:'PATCH',prefer:'return=minimal',body:{stripe_customer_id:customer.id,billing_updated_at:new Date().toISOString()}});return customer.id;}
function baseUrl(req){if(APP_URL)return APP_URL.startsWith('http')?APP_URL:`https://${APP_URL}`;const proto=req.headers['x-forwarded-proto']||'https';const host=req.headers['x-forwarded-host']||req.headers.host;return `${proto}://${host}`;}
async function createCheckoutSession(req,client){const sub=await readSubscription(client.id);if(!sub)throw new Error('NO_ACTIVE_PLAN');if(sub.stripe_subscription_id&&['active','trialing','past_due'].includes(String(sub.stripe_status||'')))throw new Error('SUBSCRIPTION_ALREADY_EXISTS');const plan=Array.isArray(sub.nsr_plans)?sub.nsr_plans[0]:sub.nsr_plans;if(!plan?.stripe_monthly_price_id)throw new Error('STRIPE_PRICE_NOT_CONFIGURED');const customerId=await ensureStripeCustomer(client,sub);const url=baseUrl(req);const params={mode:'subscription',customer:customerId,success_url:`${url}/billing.html?billing=success&session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${url}/billing.html?billing=cancel`,'line_items[0][price]':plan.stripe_monthly_price_id,'line_items[0][quantity]':1,'subscription_data[metadata][nsr_client_id]':client.id,'subscription_data[metadata][plan_code]':sub.plan_code,'metadata[nsr_client_id]':client.id,'metadata[plan_code]':sub.plan_code};if(plan.stripe_setup_price_id){params['line_items[1][price]']=plan.stripe_setup_price_id;params['line_items[1][quantity]']=1;}const session=await stripe('checkout/sessions',params);return {url:session.url,id:session.id};}
async function createPortalSession(req,client){const sub=await readSubscription(client.id);if(!sub?.stripe_customer_id)throw new Error('NO_STRIPE_CUSTOMER');const url=baseUrl(req);const session=await stripe('billing_portal/sessions',{customer:sub.stripe_customer_id,return_url:`${url}/billing.html`});return {url:session.url,id:session.id};}
async function syncCheckoutSession(client,sessionId){if(!sessionId||!/^cs_/.test(sessionId))throw new Error('INVALID_CHECKOUT_SESSION');const data=await stripeGet(`checkout/sessions/${encodeURIComponent(sessionId)}`,'expand[]=subscription&expand[]=subscription.items.data.price');if(String(data.metadata?.nsr_client_id||'')!==String(client.id))throw new Error('CHECKOUT_CLIENT_MISMATCH');const stripeSub=data.subscription&&typeof data.subscription==='object'?data.subscription:null;if(!stripeSub)throw new Error('SUBSCRIPTION_NOT_READY');const patch=await persistStripeSubscription(client.id,stripeSub,data.customer||null);return {status:patch.stripe_status,subscription_id:stripeSub.id,price_id:patch.stripe_price_id};}
function verifyWebhook(rawBody,signatureHeader){if(!STRIPE_WEBHOOK_SECRET)throw new Error('STRIPE_WEBHOOK_NOT_CONFIGURED');const parts=String(signatureHeader||'').split(',').map(x=>x.trim());const timestamp=parts.find(x=>x.startsWith('t='))?.slice(2);const signatures=parts.filter(x=>x.startsWith('v1=')).map(x=>x.slice(3));if(!timestamp||!signatures.length)throw new Error('INVALID_STRIPE_SIGNATURE');if(Math.abs(Math.floor(Date.now()/1000)-Number(timestamp))>300)throw new Error('STALE_STRIPE_SIGNATURE');const expected=crypto.createHmac('sha256',STRIPE_WEBHOOK_SECRET).update(`${timestamp}.${rawBody}`).digest('hex');const valid=signatures.some(sig=>{const a=Buffer.from(sig);const b=Buffer.from(expected);return a.length===b.length&&crypto.timingSafeEqual(a,b);});if(!valid)throw new Error('INVALID_STRIPE_SIGNATURE');}
async function processWebhook(rawBody,signatureHeader){verifyWebhook(rawBody,signatureHeader);const event=JSON.parse(rawBody);const existing=await sb(`nsr_billing_events?id=eq.${encodeURIComponent(event.id)}&select=id&limit=1`);if(Array.isArray(existing)&&existing.length)return {duplicate:true,event_id:event.id};const obj=event?.data?.object||{};const clientId=await findClientIdForStripeObject(obj);if(clientId){if(event.type.startsWith('customer.subscription.')){await persistStripeSubscription(clientId,obj,typeof obj.customer==='string'?obj.customer:obj.customer?.id||null);}else if(event.type==='checkout.session.completed'&&obj.subscription){const subId=typeof obj.subscription==='string'?obj.subscription:obj.subscription.id;const stripeSub=await stripeGet(`subscriptions/${encodeURIComponent(subId)}`,'expand[]=items.data.price');await persistStripeSubscription(clientId,stripeSub,typeof obj.customer==='string'?obj.customer:obj.customer?.id||null);}else if(event.type==='invoice.paid'){await sb(`nsr_client_subscriptions?client_id=eq.${encodeURIComponent(clientId)}`,{method:'PATCH',prefer:'return=minimal',body:{last_payment_at:new Date().toISOString(),stripe_status:'active',billing_updated_at:new Date().toISOString()}});try{await sendPaidInvoiceEmail(clientId,obj);}catch(error){console.error('PAID INVOICE NOTIFICATION ERROR:',error);}}else if(event.type==='invoice.payment_failed'){await sb(`nsr_client_subscriptions?client_id=eq.${encodeURIComponent(clientId)}`,{method:'PATCH',prefer:'return=minimal',body:{stripe_status:'past_due',billing_updated_at:new Date().toISOString()}});}}await sb('nsr_billing_events',{method:'POST',prefer:'return=minimal',body:{id:event.id,event_type:event.type,client_id:clientId||null,stripe_customer_id:typeof obj.customer==='string'?obj.customer:obj.customer?.id||null,stripe_subscription_id:typeof obj.subscription==='string'?obj.subscription:obj.subscription?.id||(event.type.startsWith('customer.subscription.')?obj.id:null)}});return {duplicate:false,event_id:event.id,event_type:event.type,client_id:clientId||null};}
module.exports={getSubscription,createCheckoutSession,createPortalSession,syncCheckoutSession,processWebhook};
