const SUPABASE_URL=process.env.SUPABASE_URL;
const SUPABASE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const {safeErrorLog}=require('../lib/nsr-safe-log');
const headers={apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json'};
const clean=(v,n=500)=>String(v??'').trim().slice(0,n);
const slugOk=v=>/^[a-z0-9_-]{2,80}$/.test(v);
const idOk=v=>/^[A-Za-z0-9._:-]{8,180}$/.test(v);
async function db(path,opt={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method:opt.method||'GET',headers:{...headers,Prefer:opt.prefer||'return=representation'},body:opt.body?JSON.stringify(opt.body):undefined,signal:AbortSignal.timeout(12000)});const t=await r.text();if(!r.ok)throw Error(`DB_${r.status}`);return t?JSON.parse(t):[];}
async function getClient(slug){const rows=await db(`clients?slug=eq.${encodeURIComponent(slug)}&select=id,config&limit=1`);const c=rows[0];if(!c||c.config?.active===false)return null;return c;}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({success:false,error:'Method not allowed'});try{if(!SUPABASE_URL||!SUPABASE_KEY)return res.status(500).json({success:false,error:'Configuration error'});const action=clean(req.body?.action,30);const slug=clean(req.body?.client_slug,80).toLowerCase();const visitorId=clean(req.body?.visitor_id,180);const sessionId=clean(req.body?.session_id,180);if(!slugOk(slug))return res.status(400).json({success:false,error:'Invalid client'});const c=await getClient(slug);if(!c)return res.status(404).json({success:false,error:'Client not found'});
if(action==='visit'){if(!idOk(visitorId))return res.status(400).json({success:false,error:'Invalid visitor'});await db('bsr_assistant_visits',{method:'POST',prefer:'return=minimal',body:{client_id:c.id,visitor_id:visitorId,session_id:idOk(sessionId)?sessionId:null}});return res.json({success:true});}
if(action==='feedback'){if(!idOk(sessionId))return res.status(400).json({success:false,error:'Invalid session'});if(typeof req.body?.resolved!=='boolean')return res.status(400).json({success:false,error:'Resolution answer required'});const conv=await db(`conversations?client_id=eq.${c.id}&session_id=eq.${encodeURIComponent(sessionId)}&select=id&limit=1`);const conversationId=conv[0]?.id||null;const note=clean(req.body?.note,1000)||null;await db('bsr_conversation_feedback',{method:'POST',prefer:'return=minimal',body:{client_id:c.id,conversation_id:conversationId,session_id:sessionId,resolved:req.body.resolved,note}});if(conversationId)await db(`conversations?id=eq.${conversationId}&client_id=eq.${c.id}`,{method:'PATCH',prefer:'return=minimal',body:{resolved_by_ai:req.body.resolved,status:'closed',ended_at:new Date().toISOString()}});return res.json({success:true});}
return res.status(400).json({success:false,error:'Invalid action'});
}catch(e){safeErrorLog('ASSISTANT_EVENTS_ERROR',e);return res.status(500).json({success:false,error:'Unable to record event'});}};