const crypto=require('crypto');
const SUPABASE_URL=process.env.SUPABASE_URL;
const SUPABASE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const STRIPE_SECRET_KEY=process.env.STRIPE_SECRET_KEY;
const COOKIE_NAME='novaire_client_session';
const SESSION_HOURS=8;
const LOGIN_MAX_ATTEMPTS=5;
const LOGIN_WINDOW_SECONDS=15*60;
const LOGIN_LOCK_SECONDS=15*60;
const LOGIN_LOCK_MS=LOGIN_LOCK_SECONDS*1000;
const fallbackLoginAttempts=new Map();
let loginStoreUnavailable=false;
const {getClientSession}=require('./_client-session');
const {currentUsage}=require('../lib/nsr-usage');
const {getSubscription,createCheckoutSession,createPortalSession,syncCheckoutSession,processWebhook}=require('../lib/nsr-billing');
const {safeErrorLog}=require('../lib/nsr-safe-log');
module.exports.config={api:{bodyParser:false}};
function safeEqual(a,b){const aa=Buffer.from(String(a||''));const bb=Buffer.from(String(b||''));return aa.length===bb.length&&crypto.timingSafeEqual(aa,bb);}
function hashPassword(password,salt){return crypto.scryptSync(String(password||''),salt,64).toString('hex');}
function sign(value){const secret=process.env.NOVAIRE_CLIENT_SESSION_SECRET;if(!secret)return'';return crypto.createHmac('sha256',secret).update(value).digest('hex');}
function clearClientCookie(res){res.setHeader('Set-Cookie',`${COOKIE_NAME}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`);}
function clientIp(req){const forwarded=String(req.headers['x-forwarded-for']||'').split(',')[0].trim();return forwarded||String(req.socket?.remoteAddress||'unknown');}
function loginKey(req,identity){return `${clientIp(req)}:${identity}`;}
function localLoginState(key){const state=fallbackLoginAttempts.get(key);if(!state)return null;if(state.lockUntil&&state.lockUntil<=Date.now()){fallbackLoginAttempts.delete(key);return null;}if(!state.lockUntil&&state.windowStartedAt&&state.windowStartedAt+LOGIN_LOCK_MS<=Date.now()){fallbackLoginAttempts.delete(key);return null;}return state;}
function localRecordFailure(key){const now=Date.now();const current=localLoginState(key)||{count:0,lockUntil:0,windowStartedAt:now};const count=current.count+1;const lockUntil=count>=LOGIN_MAX_ATTEMPTS?now+LOGIN_LOCK_MS:0;const next={count,lockUntil,windowStartedAt:current.windowStartedAt||now};fallbackLoginAttempts.set(key,next);return next;}
function localClearFailures(key){fallbackLoginAttempts.delete(key);}
function normalizeLoginState(rows){const row=Array.isArray(rows)?rows[0]:rows;if(!row)return null;const lockUntil=row.lock_until?Date.parse(row.lock_until):0;return{count:Number(row.failure_count||0),lockUntil:Number.isFinite(lockUntil)?lockUntil:0};}
function loginStoreMissing(error){return /Could not find the function|PGRST202|nsr_login_attempts.*does not exist|schema cache|Supabase login RPC 404/i.test(String(error?.message||''));}
async function loginRpc(name,body={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const text=await r.text();if(!r.ok)throw new Error(`Supabase login RPC ${r.status}: ${text}`);return text?JSON.parse(text):null;}
async function getLoginState(key){if(loginStoreUnavailable)return localLoginState(key);try{return normalizeLoginState(await loginRpc('nsr_get_login_state',{p_key:key,p_window_seconds:LOGIN_WINDOW_SECONDS}));}catch(error){if(!loginStoreMissing(error))throw error;loginStoreUnavailable=true;return localLoginState(key);}}
async function recordLoginFailure(key){if(loginStoreUnavailable)return localRecordFailure(key);try{return normalizeLoginState(await loginRpc('nsr_record_login_failure',{p_key:key,p_max_attempts:LOGIN_MAX_ATTEMPTS,p_window_seconds:LOGIN_WINDOW_SECONDS,p_lock_seconds:LOGIN_LOCK_SECONDS}));}catch(error){if(!loginStoreMissing(error))throw error;loginStoreUnavailable=true;return localRecordFailure(key);}}
async function clearLoginFailures(key){if(loginStoreUnavailable){localClearFailures(key);return;}try{await loginRpc('nsr_clear_login_failures',{p_key:key});}catch(error){if(!loginStoreMissing(error))throw error;loginStoreUnavailable=true;localClearFailures(key);}}
async function readRaw(req){const chunks=[];for await(const chunk of req)chunks.push(Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk));return Buffer.concat(chunks).toString('utf8');}
async function db(path){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`}});if(!r.ok)throw new Error('Unable to load data');const rows=await r.json();return Array.isArray(rows)?rows:[];}
async function getClientById(id){const rows=await db(`clients?id=eq.${encodeURIComponent(id)}&select=id,name,slug,config&limit=1`);return rows[0]||null;}
async function getPortalUser(email){const rows=await db(`bsr_client_portal_users?email=eq.${encodeURIComponent(email)}&active=eq.true&select=id,client_id,email,role,password_hash,password_salt&limit=1`);return rows[0]||null;}
function validEmail(value){const email=String(value||'').trim().toLowerCase();return email.length<=254&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)?email:'';}
async function validateBillingSyncSession(client,sessionId){if(!STRIPE_SECRET_KEY)throw new Error('STRIPE_NOT_CONFIGURED');if(!/^cs_[A-Za-z0-9_]+$/.test(sessionId))throw new Error('INVALID_CHECKOUT_SESSION');const r=await fetch(`https://api.stripe.com/v1/checkout/sessions/${encodeURIComponent(sessionId)}`,{headers:{Authorization:`Bearer ${STRIPE_SECRET_KEY}`}});const data=await r.json();if(!r.ok)throw new Error('INVALID_CHECKOUT_SESSION');if(data.mode!=='subscription'||data.status!=='complete'||!['paid','no_payment_required'].includes(String(data.payment_status||'')))throw new Error('CHECKOUT_NOT_COMPLETE');if(String(data.metadata?.nsr_client_id||'')!==String(client.id))throw new Error('CHECKOUT_CLIENT_MISMATCH');const sub=await getSubscription(client.id);if(sub?.plan_code&&String(data.metadata?.plan_code||'')!==String(sub.plan_code))throw new Error('CHECKOUT_PLAN_MISMATCH');const checkoutCustomer=typeof data.customer==='string'?data.customer:data.customer?.id;if(sub?.stripe_customer_id&&checkoutCustomer&&String(checkoutCustomer)!==String(sub.stripe_customer_id))throw new Error('CHECKOUT_CUSTOMER_MISMATCH');}
function safeBillingStatus(sub){if(!sub)return null;const plan=Array.isArray(sub.nsr_plans)?sub.nsr_plans[0]:sub.nsr_plans;return{plan_code:sub.plan_code,plan_name:plan?.name||sub.plan_code,status:sub.status,stripe_status:sub.stripe_status||null,auto_renew:!!sub.auto_renew,cancel_at_period_end:!!sub.cancel_at_period_end,current_period_end:sub.stripe_current_period_end||sub.cycle_end||null,stripe_customer_ready:!!sub.stripe_customer_id,stripe_subscription_ready:!!sub.stripe_subscription_id,payment_configured:!!plan?.stripe_monthly_price_id};}
function safeUsage(u){if(!u)return null;return{plan_code:u.plan_code||null,plan_name:u.plan_name||null,monthly_limit:Number(u.monthly_limit||0),used:Number(u.used||0),remaining:Number(u.remaining||0),usage_percent:Number(u.usage_percent||0),cycle_start:u.cycle_start||null,cycle_end:u.cycle_end||null,subscription_status:u.subscription_status||null,warning_level:u.warning_level||'NORMAL'};}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({success:false,error:'Method not allowed'});if(!SUPABASE_URL||!SUPABASE_KEY)return res.status(500).json({success:false,error:'Server configuration error'});try{const raw=await readRaw(req);const stripeSignature=req.headers['stripe-signature'];if(stripeSignature){const result=await processWebhook(raw,String(stripeSignature));return res.status(200).json({received:true,...result});}let body={};try{body=raw?JSON.parse(raw):{};}catch{return res.status(400).json({success:false,error:'Invalid JSON'});}const action=String(body.action||'login').trim().toLowerCase();if(action==='logout'){clearClientCookie(res);return res.status(200).json({success:true,authenticated:false});}
if(action.startsWith('billing_')){const session=getClientSession(req);if(!session)return res.status(401).json({success:false,error:'Unauthorized'});const client=await getClientById(session.client_id);if(!client||client.config?.active===false)return res.status(403).json({success:false,error:'Client inactive'});if(action==='billing_status'){try{const [sub,usage]=await Promise.all([getSubscription(client.id),currentUsage(client.id).catch(()=>null)]);return res.status(200).json({success:true,billing_ready:true,billing:safeBillingStatus(sub),usage:safeUsage(usage)});}catch(error){if(/column .* does not exist|relation .* does not exist|schema cache/i.test(error.message))return res.status(200).json({success:true,billing_ready:false,billing:null,usage:null});throw error;}}if(action==='billing_checkout')return res.status(409).json({success:false,error:'Online payment is not enabled yet'});if(action==='billing_portal')return res.status(409).json({success:false,error:'Online payment is not enabled yet'});if(action==='billing_sync'){const sessionId=String(body.session_id||'').trim();await validateBillingSyncSession(client,sessionId);return res.status(200).json({success:true,billing:await syncCheckoutSession(client,sessionId)});}return res.status(400).json({success:false,error:'Unknown billing action'});}
const email=validEmail(body.email),password=String(body.password||'');if(!email||!password)return res.status(400).json({success:false,error:'أدخل البريد الإلكتروني وكلمة المرور.'});const key=loginKey(req,email);const state=await getLoginState(key);if(state?.lockUntil>Date.now()){const retryAfter=Math.max(1,Math.ceil((state.lockUntil-Date.now())/1000));res.setHeader('Retry-After',String(retryAfter));return res.status(429).json({success:false,error:'تم إيقاف محاولات الدخول مؤقتًا. حاول مرة أخرى لاحقًا.'});}
const user=await getPortalUser(email);let valid=false;if(user?.password_hash&&user?.password_salt){try{valid=safeEqual(hashPassword(password,user.password_salt),user.password_hash);}catch{valid=false;}}if(!user||!valid){const failed=await recordLoginFailure(key);if(failed?.lockUntil){const retryAfter=Math.max(1,Math.ceil((failed.lockUntil-Date.now())/1000));res.setHeader('Retry-After',String(retryAfter));return res.status(429).json({success:false,error:'تم إيقاف محاولات الدخول مؤقتًا. حاول مرة أخرى لاحقًا.'});}return res.status(401).json({success:false,error:'بيانات الدخول غير صحيحة.'});}
const client=await getClientById(user.client_id);if(!client||client.config?.active===false)return res.status(401).json({success:false,error:'بيانات الدخول غير صحيحة.'});await clearLoginFailures(key);const expires=Date.now()+SESSION_HOURS*60*60*1000;const payload=Buffer.from(JSON.stringify({client_id:client.id,client_slug:client.slug,portal_user_id:user.id,portal_role:user.role,expires})).toString('base64url');const signature=sign(payload);if(!signature)return res.status(500).json({success:false,error:'Session configuration error'});res.setHeader('Set-Cookie',`${COOKIE_NAME}=${encodeURIComponent(`${payload}.${signature}`)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${SESSION_HOURS*60*60}`);return res.status(200).json({success:true,authenticated:true,client:{name:client.name,slug:client.slug},user:{email:user.email,role:user.role}});
}catch(error){safeErrorLog('CLIENT_AUTH_ERROR',error);const message=String(error?.message||'');if(['INVALID_STRIPE_SIGNATURE','STALE_STRIPE_SIGNATURE'].includes(message))return res.status(400).json({success:false,error:'Invalid Stripe signature'});if(message==='STRIPE_WEBHOOK_NOT_CONFIGURED')return res.status(503).json({success:false,error:'Stripe webhook is not configured yet'});return res.status(500).json({success:false,error:'Server error'});}};
