const crypto=require('crypto');
const SUPABASE_URL=process.env.SUPABASE_URL;
const SUPABASE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const {isAdminSession}=require('./_admin-session');

async function sb(path,options={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method:options.method||'GET',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json',...(options.prefer?{Prefer:options.prefer}:{})},body:options.body?JSON.stringify(options.body):undefined});const t=await r.text();if(!r.ok)throw new Error(`Supabase ${r.status}: ${t}`);return t?JSON.parse(t):null;}
async function rpc(name,body={}){return sb(`rpc/${name}`,{method:'POST',body});}
function clean(v){return String(v||'').trim();}
function slugify(v){return clean(v).toLowerCase().replace(/\s+/g,'-').replace(/[^a-z0-9_-]/g,'').replace(/-+/g,'-').replace(/^-+|-+$/g,'');}
function lang(v){return v==='en'?'en':'ar';}
function arr(v){return Array.isArray(v)?v.map(clean).filter(Boolean):[];}
function prices(v){return Array.isArray(v)?v.map(x=>{if(!x||typeof x!=='object')return null;const label=clean(x.label),price=Number(x.price);if(!label||!Number.isFinite(price))return null;return{label,price,unit_ar:clean(x.unit_ar),unit_en:clean(x.unit_en)}}).filter(Boolean):[];}
function hashPortalPassword(password){const salt=crypto.randomBytes(16).toString('hex');const hash=crypto.scryptSync(String(password),salt,64).toString('hex');return{portal_password_hash:hash,portal_password_salt:salt};}
function stripSecrets(config){if(!config||typeof config!=='object')return config;const {portal_password,portal_password_hash,portal_password_salt,...safe}=config;return safe;}
function safeClient(client){if(!client||typeof client!=='object')return client;return{...client,config:stripSecrets(client.config)};}
function configFrom(body,name,existing={}){const months=Number(body.contract_term_months||0);const base={...existing};delete base.portal_password;const password=String(body.portal_password||'');const credentials=password?hashPortalPassword(password):{};return{...base,...credentials,brand_name:clean(body.brand_name)||name,logo_url:clean(body.logo_url),contact_name:clean(body.contact_name),contact_phone:clean(body.contact_phone),contact_email:clean(body.contact_email),billing_email:clean(body.billing_email)||clean(body.contact_email),website_url:clean(body.website_url),client_legal_name:clean(body.client_legal_name),client_license_no:clean(body.client_license_no),client_signatory_name:clean(body.client_signatory_name),client_signatory_title:clean(body.client_signatory_title),contract_start_date:clean(body.contract_start_date),contract_end_date:clean(body.contract_end_date),contract_term_months:Number.isFinite(months)&&months>0?Math.min(Math.round(months),120):null,contract_status:clean(body.contract_status)||existing.contract_status||'draft',assistant_name_ar:clean(body.assistant_name_ar),assistant_name_en:clean(body.assistant_name_en),business_type_ar:clean(body.business_type_ar),business_type_en:clean(body.business_type_en),location_ar:clean(body.location_ar),location_en:clean(body.location_en),working_hours_ar:clean(body.working_hours_ar),working_hours_en:clean(body.working_hours_en),services_ar:arr(body.services_ar),services_en:arr(body.services_en),rental_prices:prices(body.rental_prices),notes_ar:clean(body.notes_ar),notes_en:clean(body.notes_en),welcome_message_ar:clean(body.welcome_message_ar),welcome_message_en:clean(body.welcome_message_en),default_language:lang(body.default_language),active:body.active!==false};}
async function getClient(id){const rows=await sb(`clients?id=eq.${encodeURIComponent(id)}&select=id,name,slug,config,created_at&limit=1`);return Array.isArray(rows)?rows[0]||null:null;}

async function listClients(){const rows=await sb('clients?select=id,name,slug,config,created_at&order=created_at.desc');const clients=(Array.isArray(rows)?rows:[]).map(row=>{const c=row.config&&typeof row.config==='object'?row.config:{};return{id:row.id,name:row.name,slug:row.slug,created_at:row.created_at,active:c.active!==false,business_type_ar:clean(c.business_type_ar),business_type_en:clean(c.business_type_en),location_ar:clean(c.location_ar),location_en:clean(c.location_en),logo_url:clean(c.logo_url),brand_name:clean(c.brand_name)||row.name,contact_name:clean(c.contact_name),contact_phone:clean(c.contact_phone),contact_email:clean(c.contact_email),billing_email:clean(c.billing_email),website_url:clean(c.website_url),client_legal_name:clean(c.client_legal_name),client_license_no:clean(c.client_license_no),client_signatory_name:clean(c.client_signatory_name),client_signatory_title:clean(c.client_signatory_title),contract_start_date:clean(c.contract_start_date),contract_end_date:clean(c.contract_end_date),contract_term_months:Number(c.contract_term_months||0)||null,contract_status:clean(c.contract_status)||'draft'}});try{const usage=await sb('nsr_admin_usage_overview?select=*&order=usage_percent.desc');const map=new Map((Array.isArray(usage)?usage:[]).map(x=>[String(x.client_id),x]));return clients.map(c=>({...c,package_usage:map.get(String(c.id))||null}));}catch(e){console.warn('PACKAGE OVERVIEW UNAVAILABLE:',e.message);return clients.map(c=>({...c,package_usage:null}));}}
async function plans(){try{const rows=await sb('nsr_plans?active=eq.true&select=code,name,setup_fee_aed,monthly_fee_aed,monthly_ai_responses&order=monthly_ai_responses.asc');return{ready:true,plans:Array.isArray(rows)?rows:[]};}catch(e){console.warn('PACKAGE TABLES UNAVAILABLE:',e.message);return{ready:false,plans:[]};}}
async function usageOverview(){try{const rows=await sb('nsr_admin_usage_overview?select=*&order=usage_percent.desc');return{ready:true,clients:Array.isArray(rows)?rows:[]};}catch(e){console.warn('PACKAGE OVERVIEW UNAVAILABLE:',e.message);return{ready:false,clients:[]};}}
async function legacyCreate(body){const name=clean(body.name),slug=slugify(body.slug);if(!name)return{status:400,data:{error:'Client name is required'}};if(!slug||slug.length<2||slug.length>80)return{status:400,data:{error:'Valid slug is required'}};const dup=await sb(`clients?slug=eq.${encodeURIComponent(slug)}&select=id&limit=1`);if(Array.isArray(dup)&&dup.length)return{status:409,data:{error:'Client slug already exists'}};const created=await sb('clients',{method:'POST',prefer:'return=representation',body:{name,slug,config:configFrom(body,name)}});if(!Array.isArray(created)||!created.length)throw new Error('Client creation failed');return{status:201,data:{success:true,client:safeClient(created[0])}};}
async function createWithPlan(body){const name=clean(body.name),slug=slugify(body.slug),planCode=clean(body.plan_code);if(!name||!slug)return{status:400,data:{error:'اسم العميل والرابط مطلوبان'}};if(!planCode)return{status:400,data:{error:'يجب اختيار الباقة'}};const config=configFrom(body,name);let rows;try{rows=await rpc('nsr_admin_create_client_with_plan',{p_name:name,p_slug:slug,p_plan_code:planCode,p_config:config,p_custom_ai_limit:body.custom_ai_limit?Number(body.custom_ai_limit):null,p_setup_fee_override_aed:body.setup_fee_override_aed!==''&&body.setup_fee_override_aed!=null?Number(body.setup_fee_override_aed):null,p_monthly_fee_override_aed:body.monthly_fee_override_aed!==''&&body.monthly_fee_override_aed!=null?Number(body.monthly_fee_override_aed):null});}catch(e){if(/Could not find the function|PGRST202|schema cache|nsr_admin_create_client_with_plan/i.test(e.message))return{status:503,data:{error:'نظام الباقات جاهز في الكود لكنه يحتاج تشغيل ملفات SQL في Supabase أولاً'}};if(/slug already exists/i.test(e.message))return{status:409,data:{error:'الرابط مستخدم لعميل آخر'}};throw e;}const row=Array.isArray(rows)?rows[0]:rows;return{status:201,data:{success:true,client:{id:row?.client_id,name:row?.client_name,slug:row?.client_slug},plan:{code:row?.plan_code,name:row?.plan_name,monthly_ai_responses:row?.monthly_limit,setup_fee_aed:row?.setup_fee_aed,monthly_fee_aed:row?.monthly_fee_aed},subscription:{cycle_start:row?.cycle_start,cycle_end:row?.cycle_end}}};}
async function assignPlan(body){const clientId=clean(body.client_id),planCode=clean(body.plan_code);if(!clientId||!planCode)return{status:400,data:{error:'client_id and plan_code are required'}};try{const rows=await rpc('nsr_admin_assign_plan',{p_client_id:clientId,p_plan_code:planCode,p_custom_ai_limit:body.custom_ai_limit?Number(body.custom_ai_limit):null,p_setup_fee_override_aed:body.setup_fee_override_aed!==''&&body.setup_fee_override_aed!=null?Number(body.setup_fee_override_aed):null,p_monthly_fee_override_aed:body.monthly_fee_override_aed!==''&&body.monthly_fee_override_aed!=null?Number(body.monthly_fee_override_aed):null});return{status:200,data:{success:true,subscription:Array.isArray(rows)?rows[0]:rows}};}catch(e){if(/Could not find the function|PGRST202|schema cache/i.test(e.message))return{status:503,data:{error:'شغّل nsr1-packages-v3.sql في Supabase أولاً'}};throw e;}}
async function updateClient(body){const id=clean(body.client_id);if(!id)return{status:400,data:{error:'client_id is required'}};const existing=await getClient(id);if(!existing)return{status:404,data:{error:'Client not found'}};const name=clean(body.name)||existing.name,slug=slugify(body.slug)||existing.slug;if(slug!==existing.slug){const dup=await sb(`clients?slug=eq.${encodeURIComponent(slug)}&id=neq.${encodeURIComponent(id)}&select=id&limit=1`);if(Array.isArray(dup)&&dup.length)return{status:409,data:{error:'Client slug already exists'}};}const updated=await sb(`clients?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',prefer:'return=representation',body:{name,slug,config:configFrom(body,name,existing.config||{})}});return{status:200,data:{success:true,client:Array.isArray(updated)?safeClient(updated[0]):null}};}
async function toggleClient(body){const id=clean(body.client_id);if(!id)return{status:400,data:{error:'client_id is required'}};const client=await getClient(id);if(!client)return{status:404,data:{error:'Client not found'}};const config=client.config&&typeof client.config==='object'?client.config:{};const active=config.active===false;await sb(`clients?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',prefer:'return=minimal',body:{config:{...config,active}}});return{status:200,data:{success:true,active}};}
async function deleteClient(body){const id=clean(body.client_id);if(!id)return{status:400,data:{error:'client_id is required'}};const client=await getClient(id);if(!client)return{status:404,data:{error:'Client not found'}};if(client.slug==='first-bike')return{status:403,data:{error:'First Bike cannot be deleted'}};await sb(`clients?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',prefer:'return=minimal'});return{status:200,data:{success:true}};}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});if(!SUPABASE_URL||!SUPABASE_KEY)return res.status(500).json({error:'Server configuration error'});if(!isAdminSession(req))return res.status(401).json({error:'Unauthorized'});try{const body=req.body||{},action=clean(body.action);if(action==='list')return res.status(200).json({success:true,clients:await listClients()});if(action==='plans'){const p=await plans();return res.status(200).json({success:true,package_system_ready:p.ready,plans:p.plans});}if(action==='usage_overview'){const u=await usageOverview();return res.status(200).json({success:true,packages_ready:u.ready,clients:u.clients,usage:u.clients});}if(action==='get'){const c=await getClient(clean(body.client_id));return c?res.status(200).json({success:true,client:safeClient(c)}):res.status(404).json({error:'Client not found'});}let result;if(action==='create')result=await legacyCreate(body);else if(action==='create_with_plan')result=await createWithPlan(body);else if(action==='assign_plan')result=await assignPlan(body);else if(action==='update')result=await updateClient(body);else if(action==='toggle')result=await toggleClient(body);else if(action==='delete')result=await deleteClient(body);else return res.status(400).json({error:'Unknown action'});return res.status(result.status).json(result.data);}catch(error){console.error('CLIENT ADMIN ERROR:',error);return res.status(500).json({error:'Unable to process client admin request'});}};
