const crypto=require('crypto');
const {getClientSession}=require('./_client-session');
const URL=process.env.SUPABASE_URL,KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const H={apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'};
const clean=v=>String(v||'').trim();
const email=v=>{const x=clean(v).toLowerCase();return x.length<=254&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x)?x:''};
async function db(path,opt={}){const r=await fetch(`${URL}/rest/v1/${path}`,{method:opt.method||'GET',headers:{...H,Prefer:opt.prefer||'return=representation'},body:opt.body?JSON.stringify(opt.body):undefined});const t=await r.text();if(!r.ok)throw new Error(`DB_${r.status}:${t}`);return t?JSON.parse(t):[];}
function hash(password,salt){return crypto.scryptSync(password,salt,64).toString('hex');}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({success:false,error:'Method not allowed'});const s=getClientSession(req);if(!s)return res.status(401).json({success:false,error:'Unauthorized'});try{const action=clean(req.body?.action);const rows=await db(`bsr_client_portal_users?client_id=eq.${encodeURIComponent(s.client_id)}&select=id,email,role,active,created_at&order=created_at.asc`);const current=rows.find(x=>x.id===s.portal_user_id);if(!current||current.active!==true)return res.status(401).json({success:false,error:'Session user inactive'});if(action==='list')return res.json({success:true,users:rows,max_users:2,current_user_id:current.id});if(current.role!=='owner')return res.status(403).json({success:false,error:'Owner permission required'});if(action==='add_member'){if(rows.length>=2)return res.status(409).json({success:false,error:'الحد الأقصى مستخدمان للحساب.'});const e=email(req.body?.email),password=String(req.body?.password||'');if(!e||password.length<10)return res.status(400).json({success:false,error:'أدخل بريدًا صحيحًا وكلمة مرور من 10 أحرف على الأقل.'});const salt=crypto.randomBytes(16).toString('hex');const created=await db('bsr_client_portal_users',{method:'POST',body:{client_id:s.client_id,email:e,role:'member',password_hash:hash(password,salt),password_salt:salt,active:true}});return res.json({success:true,user:{id:created[0].id,email:created[0].email,role:created[0].role,active:true}});}if(action==='remove_member'){const id=clean(req.body?.id);const member=rows.find(x=>x.id===id&&x.role==='member');if(!member)return res.status(404).json({success:false,error:'Additional user not found'});await db(`bsr_client_portal_users?id=eq.${encodeURIComponent(id)}&client_id=eq.${encodeURIComponent(s.client_id)}`,{method:'DELETE',prefer:'return=minimal'});return res.json({success:true});}return res.status(400).json({success:false,error:'Invalid action'});}catch(e){console.error('CLIENT_USERS_ERROR',e?.message||e);return res.status(500).json({success:false,error:'Unable to manage portal users'});}};
