const SUPABASE_URL=process.env.SUPABASE_URL;
const SUPABASE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const {isAdminSession}=require('./_admin-session');
const {safeErrorLog}=require('../lib/nsr-safe-log');
async function sb(path,options={}){if(!SUPABASE_URL||!SUPABASE_KEY)throw Error('Supabase configuration is missing');const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method:options.method||'GET',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json',...(options.prefer?{Prefer:options.prefer}:{})},body:options.body?JSON.stringify(options.body):undefined});const t=await r.text();if(!r.ok)throw Error(`Supabase ${r.status}: ${t}`);return t?JSON.parse(t):[]}
const clean=v=>typeof v==='string'?v.trim():'';
function slug(v){v=clean(v).toLowerCase();return /^[a-z0-9_-]{2,80}$/.test(v)?v:''}
async function client(s){const r=await sb(`clients?slug=eq.${encodeURIComponent(s)}&select=id,name,slug&limit=1`);return Array.isArray(r)?r[0]||null:null}
function isSupport(x){return String(x?.reason||'').trim().startsWith('[دعم NSR-1]')||String(x?.request_type||'')==='support'}
async function list(id){const r=await sb(`contact_requests?client_id=eq.${encodeURIComponent(id)}&select=id,client_id,conversation_id,request_type,customer_name,phone,reason,status,created_at&status=neq.completed&status=neq.closed&order=created_at.desc`);return (Array.isArray(r)?r:[]).filter(isSupport)}
async function update(id,requestId,status){if(!['new','in_progress','completed','closed'].includes(status))return{code:400,data:{error:'Invalid status'}};const r=await sb(`contact_requests?id=eq.${encodeURIComponent(requestId)}&client_id=eq.${encodeURIComponent(id)}&select=id,reason,request_type&limit=1`);if(!Array.isArray(r)||!r.length||!isSupport(r[0]))return{code:404,data:{error:'Support request not found'}};if(status==='completed'||status==='closed'){await sb(`contact_requests?id=eq.${encodeURIComponent(requestId)}&client_id=eq.${encodeURIComponent(id)}`,{method:'DELETE',prefer:'return=minimal'});return{code:200,data:{success:true,deleted:true}}}const u=await sb(`contact_requests?id=eq.${encodeURIComponent(requestId)}&client_id=eq.${encodeURIComponent(id)}`,{method:'PATCH',prefer:'return=representation',body:{status}});return{code:200,data:{success:true,request:Array.isArray(u)?u[0]:null}}}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});if(!SUPABASE_URL||!SUPABASE_KEY)return res.status(500).json({error:'Server configuration is incomplete'});if(!isAdminSession(req))return res.status(401).json({error:'Unauthorized'});const b=req.body||{},s=slug(b.client_slug);if(!s)return res.status(400).json({error:'Valid client_slug is required'});try{const c=await client(s);if(!c)return res.status(404).json({error:'Client not found'});if(clean(b.action)==='list')return res.status(200).json({success:true,client:c,requests:await list(c.id)});if(clean(b.action)==='update_status'){if(!clean(b.request_id))return res.status(400).json({error:'request_id is required'});const r=await update(c.id,clean(b.request_id),clean(b.status));return res.status(r.code).json(r.data)}return res.status(400).json({error:'Invalid action'})}catch(e){safeErrorLog('CONTACT_ADMIN_API_ERROR',e,{client_slug:s});return res.status(500).json({error:'Unable to manage support requests'})}};