const SUPABASE_URL=process.env.SUPABASE_URL;
const SUPABASE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const RESEND_API_KEY=process.env.RESEND_API_KEY;
const NOTIFICATION_FROM=process.env.NOVAIRE_NOTIFICATION_FROM||'BASEERA <onboarding@resend.dev>';
const FALLBACK_EMAIL=process.env.NOVAIRE_NOTIFICATION_EMAIL||'';
const {safeErrorLog}=require('../lib/nsr-safe-log');
const headers={apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json'};
const clean=(v,n=500)=>String(v??'').trim().slice(0,n);
const slugOk=v=>/^[a-z0-9_-]{2,80}$/.test(v);
const sidOk=v=>/^[A-Za-z0-9._:-]{8,180}$/.test(v);
const emailOk=v=>!v||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
const phoneOk=v=>!v||/^[0-9+()\-\s.]{5,40}$/.test(v);
async function db(path,opt={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method:opt.method||'GET',headers:{...headers,Prefer:opt.prefer||'return=representation'},body:opt.body?JSON.stringify(opt.body):undefined,signal:AbortSignal.timeout(12000)});const t=await r.text();if(!r.ok)throw Error(`DB_${r.status}`);return t?JSON.parse(t):[];}
async function client(slug){const rows=await db(`clients?slug=eq.${encodeURIComponent(slug)}&select=id,name,slug,config&limit=1`);const c=rows[0];if(!c||c.config?.active===false)return null;return c;}
async function conversation(clientId,sessionId,language){const old=await db(`conversations?client_id=eq.${clientId}&session_id=eq.${encodeURIComponent(sessionId)}&select=id&limit=1`);if(old[0])return old[0];const rows=await db('conversations',{method:'POST',body:{client_id:clientId,session_id:sessionId,status:'open',resolved_by_ai:null,human_handoff:false,callback_requested:false,language:language==='en'?'en':'ar'}});return rows[0];}
function esc(v){return String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
async function notify(c,payload){const to=clean(c.config?.contact_email||c.config?.billing_email||FALLBACK_EMAIL,254);if(!RESEND_API_KEY||!to||!emailOk(to))return false;const type=payload.request_type==='callback'?'طلب اتصال':'طلب مساعدة بشرية';const brand=c.config?.brand_name||c.name||c.slug;const subject=`BSR-1 | ${type} جديد — ${brand}`;const html=`<div dir="rtl" style="font-family:Arial,Tahoma,sans-serif;line-height:1.8"><h2>${esc(type)}</h2><p><b>المنشأة:</b> ${esc(brand)}</p><p><b>اسم الزبون:</b> ${esc(payload.customer_name)}</p><p><b>الهاتف:</b> ${esc(payload.phone||'—')}</p><p><b>البريد:</b> ${esc(payload.email||'—')}</p><p><b>السبب:</b> ${esc(payload.reason||'—')}</p><p style="color:#64748b;font-size:12px">تم إرسال هذا الإشعار من مساعد BSR-1.</p></div>`;const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:NOTIFICATION_FROM,to:[to],subject,html})});if(!r.ok)throw Error(`EMAIL_${r.status}`);return true;}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({success:false,error:'Method not allowed'});try{const b=req.body||{},slug=clean(b.client_slug,80).toLowerCase(),sid=clean(b.session_id,180),type=clean(b.request_type,30),name=clean(b.customer_name,120),phone=clean(b.phone,40),email=clean(b.email,254).toLowerCase(),reason=clean(b.reason,600),language=b.language==='en'?'en':'ar';if(!slugOk(slug)||!sidOk(sid))return res.status(400).json({success:false,error:'Invalid request'});if(!['callback','human_handoff'].includes(type))return res.status(400).json({success:false,error:'Invalid request type'});if(!name)return res.status(400).json({success:false,error:'Name is required'});if(!phone&&!email)return res.status(400).json({success:false,error:'Phone or email is required'});if(!phoneOk(phone)||!emailOk(email))return res.status(400).json({success:false,error:'Invalid contact details'});const c=await client(slug);if(!c)return res.status(404).json({success:false,error:'Client not found'});const conv=await conversation(c.id,sid,language);await db('contact_requests',{method:'POST',prefer:'return=minimal',body:{client_id:c.id,conversation_id:conv.id,request_type:type,customer_name:name,phone:phone||null,email:email||null,reason:reason||null,status:'new'}});await db(`conversations?id=eq.${conv.id}&client_id=eq.${c.id}`,{method:'PATCH',prefer:'return=minimal',body:type==='callback'?{callback_requested:true,resolved_by_ai:false}:{human_handoff:true,resolved_by_ai:false}});let emailed=false;try{emailed=await notify(c,{request_type:type,customer_name:name,phone,email,reason});}catch(e){safeErrorLog('CONTACT_V2_EMAIL_ERROR',e,{client_slug:slug});}return res.json({success:true,email_notification_sent:emailed});}catch(e){safeErrorLog('CONTACT_V2_ERROR',e);return res.status(500).json({success:false,error:'Unable to submit request'});}};