const {getClientSession}=require('./_client-session');
const {safeErrorLog}=require('../lib/nsr-safe-log');
const XLSX=require('xlsx');
const mammoth=require('mammoth');
const pdfParse=require('pdf-parse');
const URL=process.env.SUPABASE_URL,KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const headers={apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'};
const MAX_BYTES=3*1024*1024;
const clean=(v,n=500)=>String(v??'').trim().slice(0,n);
async function db(path,opt={}){const r=await fetch(`${URL}/rest/v1/${path}`,{method:opt.method||'GET',headers:{...headers,Prefer:opt.prefer||'return=representation'},body:opt.body?JSON.stringify(opt.body):undefined,signal:AbortSignal.timeout(20000)});const t=await r.text();if(!r.ok)throw Error(`DB_${r.status}`);return t?JSON.parse(t):[];}
async function getClient(id){const x=await db(`clients?id=eq.${encodeURIComponent(id)}&select=id,slug,config&limit=1`);return x[0]||null;}
async function getPlan(clientId){const s=await db(`nsr_client_subscriptions?client_id=eq.${clientId}&select=plan_code&order=created_at.desc&limit=1`);if(!s[0])return null;const p=await db(`nsr_plans?code=eq.${encodeURIComponent(s[0].plan_code)}&select=code,knowledge_file_limit&limit=1`);return p[0]||null;}
function chunks(text,size=5000){const out=[];let s=String(text||'').replace(/\u0000/g,' ').replace(/\s+/g,' ').trim();while(s){if(s.length<=size){out.push(s);break;}let cut=s.lastIndexOf(' ',size);if(cut<size*.6)cut=size;out.push(s.slice(0,cut).trim());s=s.slice(cut).trim();}return out.filter(Boolean).slice(0,80);}
async function extract(buffer,ext){if(ext==='pdf'){const x=await pdfParse(buffer);return x.text||'';}if(ext==='docx'){const x=await mammoth.extractRawText({buffer});return x.value||'';}if(['xlsx','xls'].includes(ext)){const wb=XLSX.read(buffer,{type:'buffer'});return wb.SheetNames.map(n=>`Sheet: ${n}\n${XLSX.utils.sheet_to_csv(wb.Sheets[n])}`).join('\n\n');}throw Error('UNSUPPORTED_FILE');}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({success:false,error:'Method not allowed'});const s=getClientSession(req);if(!s)return res.status(401).json({success:false,error:'Unauthorized'});let docId=null;try{const c=await getClient(s.client_id);if(!c||c.config?.active===false)return res.status(403).json({success:false,error:'Client inactive'});const fileName=clean(req.body?.file_name,180),language=req.body?.language==='en'?'en':'ar',base64=String(req.body?.base64||'').replace(/^data:[^;]+;base64,/,'');const ext=(fileName.split('.').pop()||'').toLowerCase();if(!fileName||!['pdf','docx','xlsx','xls'].includes(ext))return res.status(400).json({success:false,error:'Supported files: PDF, Word (.docx), Excel (.xlsx/.xls)'});const buffer=Buffer.from(base64,'base64');if(!buffer.length||buffer.length>MAX_BYTES)return res.status(400).json({success:false,error:'File must be 3 MB or smaller in Preview'});const p=await getPlan(c.id);const limit=Number(p?.knowledge_file_limit||0);if(!limit)return res.status(403).json({success:false,error:'No active file allowance'});const countRows=await db(`bsr_knowledge_documents?client_id=eq.${c.id}&select=id`);if(countRows.length>=limit)return res.status(409).json({success:false,error:`File limit reached (${limit})`});const doc=(await db('bsr_knowledge_documents',{method:'POST',body:{client_id:c.id,file_name:fileName,file_type:ext,file_size_bytes:buffer.length,processing_status:'processing'}}))[0];docId=doc.id;const text=await extract(buffer,ext);const parts=chunks(text);if(!parts.length)throw Error('NO_EXTRACTED_TEXT');const rows=parts.map((part,i)=>({client_id:c.id,question:`${fileName} — ${language==='ar'?'جزء':'Part'} ${i+1}`,answer:part,language,source:`file:${doc.id}:${fileName}`,active:true}));for(let i=0;i<rows.length;i+=20)await db('knowledge_base',{method:'POST',prefer:'return=minimal',body:rows.slice(i,i+20)});await db(`bsr_knowledge_documents?id=eq.${doc.id}&client_id=eq.${c.id}`,{method:'PATCH',prefer:'return=minimal',body:{processing_status:'ready',extracted_text_length:text.length,updated_at:new Date().toISOString()}});return res.json({success:true,document:{id:doc.id,file_name:fileName,parts:parts.length,characters:text.length},remaining_files:Math.max(0,limit-countRows.length-1)});}catch(e){if(docId)try{await db(`bsr_knowledge_documents?id=eq.${docId}&client_id=eq.${s.client_id}`,{method:'PATCH',prefer:'return=minimal',body:{processing_status:'failed',error_message:String(e.message||e).slice(0,500),updated_at:new Date().toISOString()}});}catch{}safeErrorLog('KNOWLEDGE_UPLOAD_ERROR',e,{client_id:s.client_id});const msg=String(e.message||e);if(msg==='UNSUPPORTED_FILE')return res.status(400).json({success:false,error:'Unsupported file'});if(msg==='NO_EXTRACTED_TEXT')return res.status(422).json({success:false,error:'No readable text found in file'});return res.status(500).json({success:false,error:'Unable to process file'});}};