const SUPABASE_URL=process.env.SUPABASE_URL;
const SUPABASE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;
const RESEND_API_KEY=process.env.RESEND_API_KEY;
const FROM=process.env.NOVAIRE_NOTIFICATION_FROM||'NOVAIRE <onboarding@resend.dev>';
const CRON_SECRET=process.env.CRON_SECRET;

async function sb(path,options={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{method:options.method||'GET',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json',...(options.prefer?{Prefer:options.prefer}:{})},body:options.body?JSON.stringify(options.body):undefined});const t=await r.text();if(!r.ok)throw new Error(`Supabase ${r.status}: ${t}`);return t?JSON.parse(t):null;}
function clean(v){return String(v||'').trim();}
function esc(v){return String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function recipients(config={}){return [...new Set([clean(config.billing_email),clean(config.contact_email)].filter(x=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x)))];}
function dayDiff(date){if(!date)return null;const now=new Date();const a=Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate());const d=new Date(date);if(Number.isNaN(d.getTime()))return null;const b=Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate());return Math.round((b-a)/86400000);}
async function wasSent(clientId,cycleStart,type,to){const q=`nsr_notification_log?client_id=eq.${encodeURIComponent(clientId)}&cycle_start=${cycleStart?`eq.${encodeURIComponent(cycleStart)}`:'is.null'}&notification_type=eq.${encodeURIComponent(type)}&recipient=eq.${encodeURIComponent(to)}&select=id&limit=1`;const rows=await sb(q);return Array.isArray(rows)&&rows.length>0;}
async function log(clientId,cycleStart,type,to,subject,status,messageId,metadata={}){await sb('nsr_notification_log',{method:'POST',prefer:'return=minimal',body:{client_id:clientId,cycle_start:cycleStart||null,notification_type:type,recipient:to,subject,status,provider_message_id:messageId||null,metadata}});}
async function email(to,subject,html){if(!RESEND_API_KEY)throw new Error('RESEND_API_KEY missing');const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:FROM,to:[to],subject,html})});const d=await r.json();if(!r.ok)throw new Error(d?.message||'Email send failed');return d?.id||null;}
function usageMessage(clientName,pct,used,limit){const urgent=pct>=100?'تم الوصول إلى الحد الشهري':pct>=90?'تنبيه عاجل للاستهلاك':pct>=75?'تنبيه استهلاك': 'إشعار استهلاك';return{subject:`NOVAIRE | ${urgent} — ${clientName}`,html:`<div dir="rtl" style="font-family:Arial,Tahoma,sans-serif;line-height:1.8;color:#111827"><h2>NOVAIRE Smart Response</h2><p>مرحبًا،</p><p>استهلاك مساعد <b>${esc(clientName)}</b> وصل إلى <b>${pct.toFixed(1)}%</b>.</p><p>الاستخدام الحالي: <b>${Number(used).toLocaleString()}</b> من <b>${Number(limit).toLocaleString()}</b> رد AI شهريًا.</p>${pct>=100?'<p><b>تم الوصول إلى الحد الحالي. يرجى التواصل معنا للترقية أو انتظار دورة التجديد حسب الباقة.</b></p>':''}<p style="font-size:12px;color:#6b7280">هذه رسالة تشغيلية آلية من NOVAIRE.</p></div>`};}
function paymentMessage(clientName,type,due,days){let title='تذكير بموعد الدفع';if(type==='payment_due_today')title='موعد الدفع اليوم';if(type.startsWith('payment_overdue'))title='تنبيه: دفعة متأخرة';const label=days===0?'اليوم':days>0?`متبقي ${days} يوم`: `متأخر ${Math.abs(days)} يوم`;return{subject:`NOVAIRE | ${title} — ${clientName}`,html:`<div dir="rtl" style="font-family:Arial,Tahoma,sans-serif;line-height:1.8;color:#111827"><h2>NOVAIRE Smart Response</h2><p>هذا تذكير بخصوص اشتراك <b>${esc(clientName)}</b>.</p><p>موعد الدفع/التجديد: <b>${esc(due)}</b> — ${esc(label)}.</p><p>يرجى التأكد من إتمام الدفع في الموعد لتجنب أي انقطاع في الخدمة.</p><p style="font-size:12px;color:#6b7280">هذه رسالة تشغيلية آلية من NOVAIRE.</p></div>`};}
async function sendOnce({clientId,cycleStart,type,to,subject,html,metadata}){if(await wasSent(clientId,cycleStart,type,to))return{skipped:true};try{const id=await email(to,subject,html);await log(clientId,cycleStart,type,to,subject,'sent',id,metadata);return{sent:true};}catch(e){try{await log(clientId,cycleStart,type,to,subject,'failed',null,{...metadata,error:e.message});}catch{}return{failed:true,error:e.message};}}
module.exports=async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='GET'&&req.method!=='POST')return res.status(405).json({error:'Method not allowed'});if(!SUPABASE_URL||!SUPABASE_KEY)return res.status(500).json({error:'Server configuration error'});if(CRON_SECRET){const auth=String(req.headers.authorization||'');if(auth!==`Bearer ${CRON_SECRET}`)return res.status(401).json({error:'Unauthorized'});}try{const [clients,usage,subs]=await Promise.all([sb('clients?select=id,name,slug,config'),sb('nsr_admin_usage_overview?select=*'),sb('nsr_client_subscriptions?select=client_id,cycle_start,cycle_end,status,stripe_status,stripe_current_period_end,last_payment_at')]);const cmap=new Map((clients||[]).map(x=>[String(x.id),x]));const smap=new Map((subs||[]).map(x=>[String(x.client_id),x]));let sent=0,skipped=0,failed=0;for(const u of (usage||[])){const client=cmap.get(String(u.client_id));if(!client)continue;const config=client.config&&typeof client.config==='object'?client.config:{};const tos=recipients(config);if(!tos.length)continue;const name=clean(config.brand_name)||client.name||client.slug;const pct=Number(u.usage_percent||0),used=Number(u.used||0),limit=Number(u.monthly_limit||0),cycleStart=u.cycle_start||null;let threshold=null;if(pct>=100)threshold=100;else if(pct>=90)threshold=90;else if(pct>=75)threshold=75;else if(pct>=50)threshold=50;if(threshold){const type=`usage_${threshold}`;const m=usageMessage(name,pct,used,limit);for(const to of tos){const r=await sendOnce({clientId:u.client_id,cycleStart,type,to,...m,metadata:{usage_percent:pct,used,limit}});sent+=r.sent?1:0;skipped+=r.skipped?1:0;failed+=r.failed?1:0;}}
const sub=smap.get(String(u.client_id));if(!sub)continue;const due=(sub.stripe_current_period_end||sub.cycle_end||'').slice(0,10);const days=dayDiff(due);let ptype=null;if(days===7)ptype='payment_due_7';else if(days===3)ptype='payment_due_3';else if(days===0)ptype='payment_due_today';else if(days===-1)ptype='payment_overdue_1';else if(days===-3)ptype='payment_overdue_3';if(ptype){const m=paymentMessage(name,ptype,due,days);for(const to of tos){const r=await sendOnce({clientId:u.client_id,cycleStart,type:ptype,to,...m,metadata:{due_date:due,days_remaining:days,stripe_status:sub.stripe_status||null}});sent+=r.sent?1:0;skipped+=r.skipped?1:0;failed+=r.failed?1:0;}}}
return res.status(200).json({success:true,sent,skipped,failed,checked:(usage||[]).length});}catch(error){console.error('NOTIFICATION CRON ERROR:',error);return res.status(500).json({error:'Unable to process notifications',detail:process.env.VERCEL_ENV==='preview'?error.message:undefined});}};
